name: emb3rs-gis-module
channels:
  - conda-forge
dependencies:
  - python==3.7.3
  - osmnx==0.11.4
  - scikit-learn==0.23.2
  - numpy==1.19.1
  - pyomo==5.7
  - haversine==2.3.0
  - pandas==1.1.3
  - folium==0.11.0
  - geopandas==0.7.0
  - shapely==1.7.0
  - networkx==2.5
  - ipykernel
  - xlrd==1.*
  - openpyxl
#
# To install this envionment use
#
#     $ conda env create -f environment.yml
#
#  or use this command
#
#     $ conda create -n emb3rs python==3.7.3 osmnx==0.11.4 networkx==2.5 shapely==1.7.0 haversine==2.3.0 folium==0.11.0 numpy==1.19.1 pyomo==5.7 geopandas==0.7.0 pandas==1.1.3 scikit-learn==0.23.2 xlrd==1.* openpyxl -c conda-forge
#
# To activate this environment, use
#
#     $ conda activate emb3rs-gis-module
#
# To deactivate an active environment, use
#
#     $ conda deactivate
#
# When using VS Code you need to start as administartor
